# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main

pool: 'Default'

steps:
  - checkout: self

  - task: Bash@3
    inputs:
      targetType: inline
      script: |
        cd $(Build.SourcesDirectory)
        ls
        pwd

  - task: ArchiveFiles@2
    inputs: 
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'tar'
      archiveFile: '$(Build.ArtifactStagingDirectory)/XYZ.tar.gz'
  
  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: 'VM-connection'
      sourceFolder: '$(Build.ArtifactStagingDirectory)'
      contents: 'XYZ.tar.gz'
      targetFolder: '/home/azureuser'
  
  - task: SSH@0
    inputs:
      sshEndpoint:  'VM-connection'
      runOptions: 'commands'
      commands: |
        sudo apt-get update
        sudo apt-get install python3
        sudo apt-get install python3-pip
        sudo apt-get install nodejs
        sudo apt-get install nginx -y
        tar -xvf /home/azureuser/XYZ.tar.gz -C /home/azureuser
        sudo rm /home/azureuser/XYZ.tar.gz
        # echo '$(Build.SourcesDirectory)'
        # echo '$(Build.ArtifactStagingDirectory)'
        # echo '$(System.DefaultWorkingDirectory)'
        # echo '$(RemotePublicFolder)'
        (cd $(FRONTENDFOLDER) && npm install && npm run build && cp -r build /var/www/html/ && exit)
        sudo systemctl restart nginx
        # (cd $(FRONTENDFOLDER) && npm run build && exit)
        # echo "In frontend folder"
        # npm install
        # npm run build
        # sudo cp -r /home/azureuser/frontend/dist /var/www/html/
        (cd $(BACKENDFOLDER) && python3 -m venv virtual-env && exit)
        (cd $(BACKENDFOLDER)/virtual-env/Scripts && activate && pip3 install -r requirements.txt && flask run --debug)
        # (cd $(BACKENDFOLDER) && pip3 install -r requirements.txt)
        # (cd $(BACKENDFOLDER) && flask run --debug)
        

#   - task: NodeTool@0
#     inputs:
#       versionSpec: '20.x'
#     displayName: 'Install Node.js'

# - script: |
#     npm install
#     npm run build
#   displayName: 'npm install and build'
